### ISSUE TITLE
MIssing Blocks for NsfIntegrate60.grc 

### ISSUE THREAD

**Issue by anthfuller** [glangsto/gr-nsf#1]
Hi @GlenLangston ,
I'm trying to get NsfIntegrate60.grc to run in GNU Radio, but I've noticed there are several grc, missing blocks or variable blocks. I'm also adding in KrakenSDR but I do own a Airspy R2 SDR if it's required?
Let me know if there is something I'm missing? Screenshot added. 

Thank you!

![Screenshot from 2022-09-28 22-18-04](https://user-images.githubusercontent.com/38588965/192923752-71d68b1b-a3bb-4358-91bc-0a1f88e20a9a.png)

**Comment by GlenLangston** [comment]
Hello Anthony,

It appears you’ve git pulled all the code you need, but
then there is are build and make steps.


Here is summary
git clone https://www.github.com/WVURAIL/gr-radio_astro
cd gr-radio_astro
git branch gr310
mkdir build
cd build
make -j 3 (if you have 4 cores)
sudo make install
sudo ldconfig

Then the blocks should be present.

Good luck 

Glen

**Comment by anthfuller** [comment]
Yeah,  figured I missed some steps!

Thank you!

**Comment by anthfuller** [comment]
That did the trick!

Thank you, Glen!! 😄

**Comment by anthfuller** [comment]
Thank you, Glen!

**Comment by anthfuller** [comment]
@GlenLangston, this is what I've changed on NSFintegrate60. Not sure if this will affect any observations I'm planning to do. 

I have the KrakenSDR setup for two RTL-SDR channels. 

![KrakenSDR_TwoChannels2](https://user-images.githubusercontent.com/38588965/193173672-b0584361-8130-44a6-bdf6-71ffdb5dba90.png)

**Comment by anthfuller** [comment]
![KrakenSDR_TwoChannels](https://user-images.githubusercontent.com/38588965/193173699-9c3fbcc7-92ad-4ecb-812f-d682a0f5bcbd.png)

**Comment by anthfuller** [comment]
I'm using an internal noise source to generate a signal by the way...

**Comment by GlenLangston** [comment]
Hi Anthony,

Very glad that worked for you.

Best regards

Glen

PS I’m at a meeting where transient detection is very important.
I hope we can consolidate our transient event work and put this in
a publication.
